spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-auth
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/usuarios/**
            - id: ms-roles
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/roles/**
            - id: ms-pacientes
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/pacientes/**
            - id: ms-pin
              uri: http://localhost:8086
              predicates:
                - Path=/api/v1/pin/**
            - id: ms-derivaciones
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/derivaciones/**
            - id: ms-examenes
              uri: http://localhost:8088
              predicates:
                - Path=/api/v1/examenes/**
            - id: ms-citas
              uri: http://localhost:8089
              predicates:
                - Path=/api/v1/citas/**
            - id: ms-notificaciones
              uri: http://localhost:8090
              predicates:
                - Path=/api/v1/notificaciones/**
            - id: ms-alertas
              uri: http://localhost:8091
              predicates:
                - Path=/api/v1/alertas/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE